name: bookworm-xfce-standard-amd64

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone minios-live Repository
      run: |
        git clone --depth 1 https://github.com/leobastiani/minios-live-gaming.git minios-live
        cd minios-live

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          debootstrap xorriso genisoimage binutils squashfs-tools \
          grub-pc-bin grub-efi-amd64-bin dosfstools mtools xz-utils zstd \
          curl rsync

    - name: Run build - Debian 12 XFCE Standard amd64
      run: |
        cd minios-live
        echo "Starting build for Debian 12 XFCE Standard amd64..."
        sudo ./minios-cmd -d bookworm -a amd64 -de xfce -pv standard -aufs -dkms -kl
        sudo mkdir -p build/output/bookworm-xfce-standard-amd64
        sudo mv build/iso/*.iso build/output/bookworm-xfce-standard-amd64/
        echo "Build completed for Debian 12 XFCE Standard amd64."

    - name: Archive build output - Debian 12 XFCE Standard amd64
      uses: actions/upload-artifact@v4
      with:
        name: minios-bookworm-xfce-standard-amd64
        path: minios-live/build/output/bookworm-xfce-standard-amd64